Add accessors to internals
fmihpc/hashinator pull request #1
Opened 2024-06-19 05:39 UTC by markusbattarbee

Used for creating batch kernels which can with one launch operate on umpteen different hash maps. Pass the kernel a pointer to the hashmap itself, and it can then act upon the contents in a limited fashion (such as doing a bulk reset)

2024-06-19 14:58 UTC, kstppd commented on include/hashinator/hashinator.h
> +   HASHINATOR_HOSTDEVICE inline KEY_TYPE expose_emptybucket() const noexcept {
There is already a method for this right?
https://github.com/kstppd/hashinator/blob/426a1c8924332a1025246503565d6206182a8743/include/hashinator/hashinator.h#L449

2024-06-19 14:58 UTC, kstppd commented on include/hashinator/hashinator.h
> +   HASHINATOR_HOSTDEVICE inline KEY_TYPE expose_tombstone() const noexcept {
Same here

2024-06-19 14:58 UTC, kstppd commented on include/hashinator/hashinator.h
> +   // Dangerous methods for exposing internals
Not a fan of these but this has been discussed.

2024-06-19 14:59 UTC, kstppd requested changes
I added some comments but I think you can remove the empty bucket and tombstone methods because those already existed.

2024-06-26 10:52 UTC, markusbattarbee commented
OK, I updated this by:
a) removing those two exposes
b) improving threadsafety
c) streamlining device insertions and making them templated for skipping existing values
d) added split wrappers for atomic Min and Max so we get rid of some ugly casting.
Passes tests on my machine.

2024-06-26 11:03 UTC, kstppd approved these changes
Passes on my machine as well

2024-06-26 11:15 UTC, merged